Выполнено задание 9 спринта
marialyahovskaya/java-filmorate pull request #2
Opened 2022-09-10 19:30 UTC by marialyahovskaya

Настроено Spring Web приложение с двумя контроллерами для обработки запросов к эндпоинтам:
- /users
- /films

2022-09-12 17:27 UTC, andrew-larkin requested changes
Привет! Очень не хватает тестов для контроллеров (см. ссылку), а также валидации для объектов модели - она поспособствует сокращению проверок.

2022-09-12 17:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
для полей класса стоит добавить валидацию - можно использовать стандартные спринговые аннотации. Это позволит значительно сократить кол-во проверок в колнтроллере

2022-09-12 17:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
то же самое что и для класса Film

2022-09-12 17:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/Controller/UserController.java
> +        if (user.getEmail() == null) {
большую часть всех этих проверок стоит убрать с помощью валидации (см. комментарий в классах моделей), а то что убрать на удастся - вынести в отдельный приватный метод (а лучше даже в отдельный класс со статическим методом)

2022-09-12 17:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/Controller/UserController.java
> +        if (!users.containsKey(user.getId())) {
так же актуально насчет проверок

2022-09-12 17:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/Controller/FilmController.java
> +    public Film create(@RequestBody Film film) throws ValidationException {
большую часть всех этих проверок стоит убрать с помощью валидации (см. комментарий в классах моделей), а то что убрать на удастся - вынести в отдельный приватный метод (а лучше даже в отдельный класс со статическим методом)

2022-09-12 17:27 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/Controller/FilmController.java
> +        if (!films.containsKey(film.getId())) {
также актуально насчет проверок

2022-09-12 17:27 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
очень не хватает тестов. я оставлю ссылку на статью  с mockMvc - вместе с ним можно быстро протестировать все методы контроллеров

2022-09-13 22:06 UTC, marialyahovskaya commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Это уже дополнительное задание :) пока пропускаю

2022-09-13 22:06 UTC, marialyahovskaya commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
Это уже дополнительное задание :) пока пропускаю

2022-09-13 22:07 UTC, marialyahovskaya commented on src/main/java/ru/yandex/practicum/filmorate/Controller/UserController.java
> +        if (user.getEmail() == null) {
валидация вынесена в отдельный класс

2022-09-13 22:07 UTC, marialyahovskaya commented on src/main/java/ru/yandex/practicum/filmorate/Controller/FilmController.java
> +    public Film create(@RequestBody Film film) throws ValidationException {
валидация вынесена в отдельный класс

2022-09-13 22:08 UTC, marialyahovskaya commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Пока что тесты реализованы в виде юнит тестов для валидаторов

2022-09-20 09:45 UTC, merged